/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/EditValueModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/FoodInfo`; params?: Router.UnknownInputParams; } | { pathname: `/components/LogsTimeline`; params?: Router.UnknownInputParams; } | { pathname: `/components/NextInjection`; params?: Router.UnknownInputParams; } | { pathname: `/context/InjectionContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/utils/dateUtils`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EditValueModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FoodInfo`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LogsTimeline`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NextInjection`; params?: Router.UnknownOutputParams; } | { pathname: `/context/InjectionContext`; params?: Router.UnknownOutputParams; } | { pathname: `/context/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/dateUtils`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/EditValueModal${`?${string}` | `#${string}` | ''}` | `/components/FoodInfo${`?${string}` | `#${string}` | ''}` | `/components/LogsTimeline${`?${string}` | `#${string}` | ''}` | `/components/NextInjection${`?${string}` | `#${string}` | ''}` | `/context/InjectionContext${`?${string}` | `#${string}` | ''}` | `/context/ThemeContext${`?${string}` | `#${string}` | ''}` | `/utils/dateUtils${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/EditValueModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/FoodInfo`; params?: Router.UnknownInputParams; } | { pathname: `/components/LogsTimeline`; params?: Router.UnknownInputParams; } | { pathname: `/components/NextInjection`; params?: Router.UnknownInputParams; } | { pathname: `/context/InjectionContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/utils/dateUtils`; params?: Router.UnknownInputParams; };
    }
  }
}
